services:
    app:
        build: .
        ports:
            - "6006:6006"
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: [ "tail", "-f", "/dev/null"]
    postgres:
        image: postgres:15
        container_name: postgres-db
        environment:
            POSTGRES_DB: keycloak_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - keycloak-network
    keycloak:
        image: quay.io/keycloak/keycloak:26.2.0
        container_name: keycloak
        volumes:
            - "keycloak_data:/opt/keycloak/data"
            - "./dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar"
        environment:
            DB_VENDOR: postgres
            DB_ADDR: postgres
            DB_DATABASE: keycloak_db
            DB_USER: admin
            DB_PASSWORD: admin
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command: >
            start-dev
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - keycloak-network
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - keycloak-network
volumes:
    postgres_data:
    keycloak_data:
networks:
    keycloak-network:
